### ISSUE TITLE
RunDiffusionMaps fails with pmat

### ISSUE THREAD

**Issue by suragnair** [r3fang/SnapATAC#157]
I'm trying to do dimensionality reduction using the `pmat` instead of `bmat`. However, the `trainRegression` function has the `bmat` hardcoded, which causes `RunDiffusionMaps` to fail.

https://github.com/r3fang/SnapATAC/blob/c3ab177558f0fe9c47cbd68969df7b06de5b07d9/R/utilities.R#L126

**Comment by shaistamadad** [comment]
Hi,
I face a similar issue when I try to run RunDiffusionMaps with pmat instead of bmat. Here is the error I get (at the trainRegression function) : 

Epoch: checking the inputs ...
Epoch: computing jaccard similarity matrix ...
Epoch: fitting regression model ...
Error in density.default(x = row.covs, bw = "nrd", adjust = 1) : 
  need at least 2 points to select a bandwidth automatically

**Comment by yuxuanChen777** [comment]
I met the same error, how can I solve this problem? please help me 
![image](https://user-images.githubusercontent.com/86239688/174062500-f5584656-cb82-40f5-9438-e44df07c95ec.png)

**Comment by suragnair** [comment]
I've pushed some fixes here https://github.com/kundajelab/SnapATAC/tree/4cb43f7, you can try this version.

**Comment by yuxuanChen777** [comment]
> I've pushed some fixes here https://github.com/kundajelab/SnapATAC/tree/4cb43f7, you can try this version.

I follow your advice trying this version, but there is still the same error.
![image](https://user-images.githubusercontent.com/86239688/174235674-d8b90d2a-66bb-454d-92f5-0ff2420a5ebb.png)

**Comment by suragnair** [comment]
Did you reinstall SnapATAC using the version I linked? You will have to uninstall the correct version and run install from the above link.

**Comment by yuxuanChen777** [comment]
> Did you reinstall SnapATAC using the version I linked? You will have to uninstall the correct version and run install from the above link.

yes, I did that

**Comment by suragnair** [comment]
Hard to say then. Perhaps you can insert some print statements around this line
`row.covs.dens <- density(x = row.covs, bw = 'nrd', adjust = 1)`
in the `trainRegression.R` function in `utilities.R` and see where it's bugging out. 

Also looks like there's a SnapATAC2 version out now https://github.com/kaizhang/SnapATAC2.

**Comment by yuxuanChen777** [comment]
> Hard to say then. Perhaps you can insert some print statements around this line `row.covs.dens <- density(x = row.covs, bw = 'nrd', adjust = 1)` in the `trainRegression.R` function in `utilities.R` and see where it's bugging out.
> 
> Also looks like there's a SnapATAC2 version out now https://github.com/kaizhang/SnapATAC2.

thank you very much. Could you tell there is the link to the SnapATAC2's source paper is?

**Comment by suragnair** [comment]
Not sure, looks like it's in development

**Comment by yuxuanChen777** [comment]
> Not sure, looks like it's in development

Okay, thank you for your reply and help
